ip=input("Enter a String.")
a=ip.split(" ")
t=tuple(a)
print("Number of Words are: ",len(t))
print("Slicing the tuple:")
x=int(input("Enter the start index: "))
y=int(input("Enter the end index: "))
z=int(input("Enter the step size: "))
print("Sliced tuple: ")
print(t[x:y:z])
str=input("Enter the word to be searched:")
print("Word available in the tuple?:",str in t)